<?php
/** @var \Magelearn\ProductsGrid\Block\Adminhtml\Post\Edit\Options\Swatch $block */
?>
<fieldset class="fieldset">
    <legend class="legend">
        <span><?php echo $block->escapeHtml(__('Manage Swatch'))?></span>
    </legend>
    <div id="swatch-visual-options-panel">
        <table class="data-table clearfix" data-index="attribute_options_select">
            <thead>
                <tr id="swatch-visual-options-table">
                    <th class="col-draggable"></th>
                    <th><span><?php echo $block->escapeHtml(__('Swatch Image')) ?></span></th>
                    <th class="col-default _required">
                        <span><?php echo $block->escapeHtml(__('Swatch Content')) ?></span>
                    </th>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="swatch-visual-options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="3" class="validation">
                    <input type="hidden" class="required-dropdown-attribute-entry"
                           name="dropdown_attribute_validation"/>
                </th>
            </tr>
            <tr>
                <th colspan="3" class="col-actions-add">
                    <button id="add_new_swatch_visual_option_button" data-action="add_new_row"
                            title="<?php echo $block->escapeHtml(__('Add Swatch')); ?>"
                            type="button" class="action- scalable add">
                        <span><?php echo $block->escapeHtml(__('Add Swatch')); ?></span>
                    </button>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="swatch-visual-option-count-check" value="" />
    </div>
    <script id="swatch-visual-row-template" type="text/x-magento-template">
        <tr>
            <td class="col-draggable">
                <div data-role="draggable-handle" class="draggable-handle"
                     title="<?php echo $block->escapeHtml(__('Sort Option')); ?>"></div>
                <input
                        data-role="order"
                        type="hidden"
                        name="option[<%- data.id %>][order]"
                        value="<%- data.sort_order %>"/>
            </td>
            <td class="swatches-visual-col col-default <%- data.empty_class %>">
                <input id="swatch_visual_value_<%- data.id %>" type="hidden"
                       name="option[<%- data.id %>][image]" value="<%- data.thumbnail %>" />
                <div class="swatch_window" id="swatch_window_option_<%- data.id %>" style="<%- data.image %>"></div>
                <div class="swatch_sub-menu_container" id="swatch_container_option_<%- data.id %>">
                    <div class="swatch_row position-relative">
                        <div class="swatch_row_name colorpicker_handler">
                            <p><?php echo $block->escapeHtml(__('Choose a color')); ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_choose_file_upload"
                             id="swatch_choose_file_option_<%- data.id %>">
                            <p><?php echo $block->escapeHtml(__('Upload a file')); ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_remove_swatch">
                            <p><?php echo $block->escapeHtml(__('Clear')); ?></p>
                        </div>
                    </div>
                </div>
            </td>
            <td class="col-<%- data.id %>">
                <input
                        name="option[<%- data.id %>][description]"
                        value="<%- data.description %>"
                        class="input-text required-option"
                        type="text"
                />
            </td>
            <td id="delete_button_swatch_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="option[<%- data.id %>][delete]" value="" />
                <button
                        id="delete_button_<%- data.id %>"
                        title="<?php echo $block->escapeHtml(__('Delete')) ?>"
                        type="button"
                        class="action- scalable delete delete-option">
                    <span><?php echo $block->escapeHtml(__('Delete')) ?></span>
                </button>
            </td>
        </tr>
    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magelearn_ProductsGrid/js/swatch": <?php /* @noEscape */ echo $block->getJsConfig(); ?>
        }
    }
    </script>
</fieldset>